config/routes.rb
Blipet::Application.routes.draw do
 
  match '/sales' => 'sales#index'
  match '/search' => 'search#index'
  get "/search/maps"

  match '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}
  match 'calendar/complete' => 'calendar#complete'

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  resources :comments

  resources :events
  resources :calendar_events

  devise_for :users,controllers: {omniauth_callbacks: "omniauth_callbacks"}

  get "home/index"
  resources :pets

  root :to => 'home#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :event_id, :owner_id, :text
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @comments }
    end
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
    @comment = Comment.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @comment }
    end
  end

  # GET /comments/new
  # GET /comments/new.json
  def new
    @comment = Comment.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @comment }
    end
  end

  # GET /comments/1/edit
  def edit
    @comment = Comment.find(params[:id])
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(params[:comment])

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment, notice: 'Comentario registrado exitosamente.' }
        format.json { render json: @comment, status: :created, location: @comment }
      else
        format.html { render action: "new" }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /comments/1
  # PUT /comments/1.json
  def update
    @comment = Comment.find(params[:id])

    respond_to do |format|
      if @comment.update_attributes(params[:comment])
        format.html { redirect_to @comment, notice: 'Comentario editado.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to comments_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> Su comentario no se pudo guardar correctamente, intente nuevamente:</h2>
      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :event_id %><br />
    <%= f.number_field :event_id %>
  </div>
  <div class="field">
    <%= f.label :owner_id %><br />
    <%= f.number_field :owner_id %>
  </div>
  <div class="field">
    <%= f.label :text %><br />
    <%= f.text_area :text %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editar comentario</h1>

<%= render 'form' %>

<%= link_to 'Mostrar', @comment %> |
<%= link_to 'Regresar', comments_path %>

app/views/comments/index.html.erb
<h1>Lista de comentarios</h1>

<table>
  <tr>
    <th>Evento</th>
    <th>Dueño</th>
    <th>Descripcion</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @comments.each do |comment| %>
  <tr>
    <td><%= comment.event_id %></td>
    <td><%= comment.owner_id %></td>
    <td><%= comment.text %></td>
    <td><%= link_to 'Mostrar', comment %></td>
    <td><%= link_to 'Editar', edit_comment_path(comment) %></td>
    <td><%= link_to 'Eliminar', comment, method: :delete, data: { confirm: '¿Esta seguro que desea eliminar su comentario?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Nuevo comentario', new_comment_path %>

app/views/comments/new.html.erb
<h1>Nuevo comentario</h1>

<%= render 'form' %>

<%= link_to 'Regresar', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Event:</b>
  <%= @comment.event_id %>
</p>

<p>
  <b>Owner:</b>
  <%= @comment.owner_id %>
</p>

<p>
  <b>Text:</b>
  <%= @comment.text %>
</p>


<%= link_to 'Editar', edit_comment_path(@comment) %> |
<%= link_to 'Regresar', comments_path %>