config/routes.rb
Blipet::Application.routes.draw do
 
  match '/sales' => 'sales#index'
  match '/search' => 'search#index'
  get "/search/maps"

  match '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}
  match 'calendar/complete' => 'calendar#complete'

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  resources :comments

  resources :events
  resources :calendar_events

  devise_for :users,controllers: {omniauth_callbacks: "omniauth_callbacks"}

  get "home/index"
  resources :pets

  root :to => 'home#index'

end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
  	@clinic_results = Clinic.search(params[:search]).paginate(:page => params[:cli_page],:per_page=>10)
  	@pet_results = Pet.search(params[:search]).paginate(:page => params[:pet_page],:per_page=>10)
  end

  def maps
	@json = Clinic.all.to_gmaps4rails do |clinic, marker|
		marker.infowindow render_to_string(:partial => "/search/clinicinfo", :locals => { :object => clinic})
		marker.json({ :id => clinic.id})
	end
  end
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/search/_clinicinfo.html.erb
<p>	<%=object.name%></p>
<p>	<%=object.address%></p>
<p>	<%=object.phone%></p>

app/views/search/_form.html.erb
<%= form_tag search_path, :method => 'get',:class=>"navbar-search pull-left" do |f|%>
    <%= text_field_tag :search, params[:search],:class=>"search-query", :placeholder=>"Búsqueda",:rel=>"tooltip",:"data-placement"=>"bottom",:"data-original-title"=>"Encuentra Clínicas Veterinarias por Nombre o Comuna, o Mascotas por Nombre y Raza",:style=>"width:180px;" %>
    <%= image_submit_tag '/assets/search.png', :name => nil%>
<% end %>

app/views/search/index.html.erb
<div class="hero-unit">
  <p>También puedes encontar clínicas mendiante un mapa de santiago </p>
  <p>
      <%=link_to "Descúbrelas", search_maps_path , :class=>"pull-right btn btn-primary btn-large"%>
  </p>
</div>


<ul class="nav nav-tabs">
  <li id="cli_ul" class="active">
    <a id="cli_link" href="#">Clinicas</a>
  </li>
  <li id="pet_ul"><a id="pet_link" href="#">Mascotas</a></li>
</ul>


<div id="clinics_search">



<table class="table table-stripped">
<thead>
<tr><th>Nombre</th><th>Dirección</th><th>Comuna</th><th>Teléfono</th></tr>
</thead>
<% @clinic_results.each do |res| %>
<tr><td><%=res.name%></td><td><%=res.address%></td><td><%=res.location%></td><td><%=res.phone%></td></tr>
<%end%>
</table>
<%= will_paginate @clinic_results, :param_name => 'cli_page'%>





</div>


<div id="pets_search" class="hide">
<table class="table table-stripped">
<thead>
<tr><th>Nombre</th><th>Especie</th><th>Raza</th><th>Dueño</th></tr>
</thead>
<% @pet_results.each do |res| %>
<tr><td><%=res.name%></td><td><%=res.specie%></td><td><%=res.race%></td><td><%=res.user.name%></td></tr>
<%end%>
</table>
<%= will_paginate @pet_results, :param_name => 'pet_page'%>
</div>

app/views/search/maps.html.erb
<%= stylesheet_link_tag 'gmaps4rails' %>
<style type="text/css">

.map_container{
	  width: 660px;
}
.gmaps4rails_map {
  width: 650px;
  height: 400px;
}
</style>


<%= gmaps4rails(@json) %>