config/routes.rb
Blipet::Application.routes.draw do
 
  match '/sales' => 'sales#index'
  match '/search' => 'search#index'
  get "/search/maps"

  match '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}
  match 'calendar/complete' => 'calendar#complete'

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  resources :comments

  resources :events
  resources :calendar_events

  devise_for :users,controllers: {omniauth_callbacks: "omniauth_callbacks"}

  get "home/index"
  resources :pets

  root :to => 'home#index'

end

app/models/event.rb
class Event < ActiveRecord::Base
belongs_to :pet
attr_accessible :date, :pet_id, :event_text, :event_type, :photo, :latitude, :longitude, :location
geocoded_by :locationb

def locationb
	[location,'Santiago','Chile'].compact.join(', ') unless location.empty?
end

after_validation :geocode, :if => :location_changed?
has_attached_file :photo,
	:styles => {
  	:thumb => "100x100#",
  	:small => "150x150"
	}

def event_type_enum
	['Paseo', 'Veterinaria', 'Deporte', 'Peluqueria', 'Otros']
end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  # GET /events
  # GET /events.json
  def index
    @events = Event.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @events }
    end
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @event = Event.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @event }
    end
  end

  # GET /events/new
  # GET /events/new.json
  def new
    @event = Event.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @event }
    end
  end

  # GET /events/1/edit
  def edit
    @event = Event.find(params[:id])
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(params[:event])

    respond_to do |format|
      if @event.save
        format.html { redirect_to session[:return_to], notice: 'Acontecimiento registrado exitosamente' }
        format.json { render json: @event, status: :created, location: @event }
      else

        format.html { redirect_to session[:return_to], alert: 'Algo ha salido mal' }

        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /events/1
  # PUT /events/1.json
  def update
    @event = Event.find(params[:id])

    respond_to do |format|
      if @event.update_attributes(params[:event])
        format.html { redirect_to @event, notice: 'Acontecimiento actualizado exitosamente.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    respond_to do |format|
      format.html { redirect_to events_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
 <div class="modal hide" id="new-event-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">

    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
      <h3 id="myModalLabel">Nuevo Evento</h3>
    </div>
    <div class="modal-body">
      <%= form_for(@event, validate: true, remote: true, html: {"data-type" => :json}) do |f| %>
      <% if @event.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@event.errors.count, "error") %> No fue posible guardar su comentario, intente nuevamente:</h2>

          <ul>
          <% @event.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
          </ul>
        </div>
      <% end %>
    <%if @pets.nil? %>
      <div style="line-height:0.1em; display: none;" class="field">
        <%= f.label :mascota %><br />
        <%= f.text_field :pet_id , :value=>@pet.id, :readonly => true%>
      </div>
    <%else %>
      <div style="line-height:0.1em;" class="field">
        <%= f.label :mascota %><br />
        <%= f.select(:pet_id, @pets.all.collect {|p| [ p.name, p.id ] })%>
      </div>
    <%end %>
      <div style="line-height:0.1em;" class="field">
        <%= f.label :tipo_de_evento %><br />
        <%= f.select :event_type, @event.event_type_enum %>
      </div>
      <div style="line-height:0.1em;" class="field">
        <%= f.label :Lugar %><br />
        <%= f.text_field :location %>
      </div>
      <div style="line-height:0.1em;" class="field">
        <%= f.label :hecho %><br />
        <%= f.text_area :event_text, :class=>"cuadro_texto" %>
      </div>
      <div style="line-height:0.1em; "class="field">
        <%= f.label :foto %><br /> 
        <%= f.file_field :photo %>
      </div>
    </div>
    <div class="modal-footer">
      <div class="actions">
        <button class="btn" data-dismiss="modal" aria-hidden="true">Cancelar</button>
        <%= f.submit "Agregar Evento", :class=>"btn btn-primary" %>
      </div>
    </div>
<% end %>

   

      

  </div>

app/views/events/edit.html.erb
<h1>Editar evento</h1>

<%= render 'form' %>

<%= link_to 'Mostrar', @event %> |
<%= link_to 'Regresar', events_path %>

app/views/events/index.html.erb
<h1>Listado de eventos</h1>

<table>
  <tr>
    <th>Mascota</th>
    <th>Tipo</th>
    <th>Fecha</th>
    <th>Descripción</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @events.each do |event| %>
  <tr>
    <td><%= event.pet.name %></td>
    <td><%= event.event_type %></td>
    <td><%= event.date %></td>
    <td><%= event.event_text %></td>
    <td><%= link_to 'Mostrar', event %></td>
    <td><%= link_to 'Editar', edit_event_path(event) %></td>
    <td><%= link_to 'Eliminar', event, method: :delete, data: { confirm: '¿Esta seguro que desea eliminar este evento?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Nuevo evento', new_event_path %>

app/views/events/new.html.erb
<h1>Nuevo evento</h1>

<%= render 'form' %>

<%= link_to 'Regresar', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Pet:</b>
  <%= @event.pet %>
</p>

<p>
  <b>Type:</b>
  <%= @event_type %>
</p>

<p>
  <b>Date:</b>
  <%= @event.date %>
</p>

<p>
  <b>Text:</b>
  <%= @event_text %>
</p>
  <%= image_tag @event.photo.url(:small) %>  
</p>


<%= link_to 'Editar', edit_event_path(@event) %> |
<%= link_to 'Regresar', events_path %>